name: spectra_cli
description: A Multi-LLM Spec-Driven Development System.
version: 0.1.0
homepage: https://github.com/iamEtornam/spectra

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  interact: ^2.1.1
  http: ^1.1.0
  yaml: ^3.1.2
  mason_logger: ^0.3.3
  xml: ^6.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
